
[[sources]]
url = "https://github.com/bailiff-io/bailiff-mod-agentic.git"

[[sources]]
url = "https://github.com/bailiff-io/bailiff-mod-apm.git"

[[sources]]
url = "https://github.com/bailiff-io/bailiff-mod-base.git"

[[sources]]
url = "https://github.com/bailiff-io/bailiff-mod-cdk.git"

[[sources]]
url = "https://github.com/bailiff-io/bailiff-mod-ci-github.git"

[[sources]]
url = "https://github.com/bailiff-io/bailiff-mod-ci-gitlab.git"

[[sources]]
url = "https://github.com/bailiff-io/bailiff-mod-cloudformation.git"

[[sources]]
url = "https://github.com/bailiff-io/bailiff-mod-github-repo.git"

[[sources]]
url = "https://github.com/bailiff-io/bailiff-mod-go.git"

[[sources]]
url = "https://github.com/bailiff-io/bailiff-mod-justfile.git"

[[sources]]
url = "https://github.com/bailiff-io/bailiff-mod-lefthook.git"

[[sources]]
url = "https://github.com/bailiff-io/bailiff-mod-package-add.git"

[[sources]]
url = "https://github.com/bailiff-io/bailiff-mod-precommit.git"

[[sources]]
url = "https://github.com/bailiff-io/bailiff-mod-python.git"

[[sources]]
url = "https://github.com/bailiff-io/bailiff-mod-quality.git"

[[sources]]
url = "https://github.com/bailiff-io/bailiff-mod-readme.git"

[[sources]]
url = "https://github.com/bailiff-io/bailiff-mod-rust.git"

[[sources]]
url = "https://github.com/bailiff-io/bailiff-mod-stack-adr.git"

[[sources]]
url = "https://github.com/bailiff-io/bailiff-mod-terraform.git"

[[sources]]
url = "https://github.com/bailiff-io/bailiff-mod-ts.git"

[[sources]]
url = "https://github.com/bailiff-io/bailiff-mod-devcontainer.git"

[[sources]]
url = "https://github.com/bailiff-io/bailiff-mod-editorconfig.git"

[[sources]]
url = "https://github.com/bailiff-io/bailiff-mod-cocogitto.git"

[[sources]]
url = "https://github.com/bailiff-io/bailiff-mod-dep-updates.git"

[[sources]]
url = "https://github.com/bailiff-io/bailiff-mod-moon.git"

[[sources]]
url = "https://github.com/bailiff-io/bailiff-mod-mkdocs.git"

[[sources]]
url = "https://github.com/bailiff-io/bailiff-mod-gitlab-repo.git"

[[sources]]
url = "https://github.com/bailiff-io/bailiff-mod-api.git"
