
[[sources]]
url = "https://github.com/copier-clerk/clerk-mod-base.git"

[[sources]]
url = "https://github.com/copier-clerk/clerk-mod-python.git"

[[sources]]
url = "https://github.com/copier-clerk/clerk-mod-apm.git"

[[sources]]
url = "https://github.com/copier-clerk/clerk-mod-package-add.git"
