"""spec 007 US2 / SC-002, Q3 (T013): [.., bailiff-mod-apm] reproduces faithfully.

Generate an APM-wired project, then reproduce and assert the install `_task`
re-runs under trust and regenerates apm.lock.yaml as EXTERNAL STATE.

Covers N=1 (apm only, via reproduce) and the multi-layer case (via reproduce_many).
Tasks are the offline stub (bailiff_mod_apm fixture).
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import pytest

from bailiff import runner, trust
from bailiff.catalog import TemplateRecord
from tests.conftest import TemplateRepo

_PKGS = [
    "srobroek/agentic-packages/packages/speckit#>=5.0.0 <6.0.0",
    "srobroek/agentic-packages/packages/dep-audit#>=1.0.0 <2.0.0",
]


@pytest.fixture(autouse=True)
def _isolated_settings(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("COPIER_SETTINGS_PATH", str(tmp_path / "settings.yml"))


def _record(full_id: str, repo: TemplateRepo, questions: list[str]) -> TemplateRecord:
    return TemplateRecord(
        full_id=full_id,
        source=repo.url,
        ref=repo.tag,
        versions=[repo.tag],
        reproducible=True,
        has_tasks=True,
        questions=questions,
    )


def test_apm_reproduce_regenerates_lock_n1(bailiff_mod_apm: TemplateRepo, tmp_path: Path) -> None:
    """SC-002 / Q3 (N=1): install task re-runs on reproduce; lock is external state."""
    trust.add_trust(bailiff_mod_apm.url)
    dest = tmp_path / "proj"
    spec = runner.RunSpec(
        source=bailiff_mod_apm.url,
        dest=str(dest),
        answers={"project_name": "myapp", "apm_packages": _PKGS},
    )
    runner.init(spec, today="2026-07-13")

    assert (dest / "apm.lock.yaml").is_file(), "install task did not write the lock"

    runner.reproduce_many(str(dest))

    # TASK-OUTPUT lock regenerated by the (re-run) install task — present, but NOT
    # asserted byte-identical (external state, Q3).
    assert (dest / "apm.lock.yaml").is_file(), "lock not regenerated by the re-run task"


def test_apm_reproduce_multi_layer(
    apm_stub_base: TemplateRepo, bailiff_mod_apm: TemplateRepo, tmp_path: Path
) -> None:
    """SC-002 / Q3 (multi-layer): [stub_base, apm] reproduces; lock regenerated."""
    trust.add_trust(apm_stub_base.url)
    trust.add_trust(bailiff_mod_apm.url)
    dest = tmp_path / "proj"

    selection: list[tuple[TemplateRecord, dict[str, Any]]] = [
        (
            _record("demo/bailiff-mod-stub-base", apm_stub_base, ["project_name"]),
            {"project_name": "myapp"},
        ),
        (
            _record("demo/bailiff-mod-apm", bailiff_mod_apm, ["project_name", "apm_packages"]),
            {"apm_packages": _PKGS},
        ),
    ]
    runner.init_many(selection, str(dest), today="2026-07-13")

    # project_name threaded from the stub base into the apm layer's rendered file.
    import yaml

    assert yaml.safe_load((dest / "apm.yml").read_text())["name"] == "myapp"

    runner.reproduce_many(str(dest))

    assert (dest / "apm.lock.yaml").is_file(), "lock not regenerated on multi-layer reproduce"
