"""clerk command-line entry point — the deterministic phase-2 surface.

Four verbs conduct the whole slice-1 loop, all runnable and testable without an
LLM (the agent, phase 1, calls these):

* ``clerk discover <src> [--ref REF]`` — print a template's static description as
  JSON (the agent reads this to author a run-spec).
* ``clerk init --run-spec FILE [--check]`` — generate a project from the frozen
  inputs; ``--check`` dry-runs validation without writing.
* ``clerk reproduce [DEST]`` — faithfully replay a project at its recorded commit.
* ``clerk trust add <prefix>`` / ``clerk trust list`` — record/list trusted sources
  (the only writer of trust; invoked on explicit human consent).

Uses stdlib ``argparse`` (no CLI-framework dependency — glue stays light). Errors
are printed legibly with a non-zero exit; no bare stack traces (FR-010).
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import date
from pathlib import Path

import yaml

from clerk import __version__, discovery, runner, trust
from clerk.errors import ClerkError, UntrustedSourceError

# The per-project reproduce recipe: faithful, version-pinned, agent-free. Written
# into the generated project so `just reproduce` can never silently upgrade.
_REPRODUCE_JUST = """\
# Generated by clerk — faithful, agent-free reproduce.
# Replays the committed answers at the recorded commit (never the latest tag).
reproduce:
    clerk reproduce .
"""


def _today() -> str:
    """clerk's own clock, injected as the frozen ``today`` answer (FR-007)."""
    return date.today().isoformat()  # noqa: DTZ011 — a calendar date is intended


def _load_run_spec(path: str) -> runner.RunSpec:
    raw = Path(path).read_text()
    data = yaml.safe_load(raw)  # JSON is valid YAML, so this accepts both
    return runner.RunSpec.from_mapping(data)


def _cmd_discover(args: argparse.Namespace) -> int:
    desc = discovery.discover(args.source, args.ref)
    print(json.dumps(desc.to_dict(), indent=2))
    return 0


def _cmd_init(args: argparse.Namespace) -> int:
    spec = _load_run_spec(args.run_spec)
    result = runner.init(spec, today=_today(), check=args.check)
    if result.pretend:
        print(f"OK: inputs valid for {spec.source} (no files written).")
    else:
        _write_reproduce_recipe(Path(spec.dest))
        print(f"OK: generated {spec.dest} from {spec.source}.")
    return 0


def _write_reproduce_recipe(dest: Path) -> None:
    """Drop a `justfile` with the version-pinned reproduce recipe (FR-015a)."""
    justfile = dest / "justfile"
    if justfile.exists():
        return  # respect a template-provided justfile; don't clobber
    justfile.write_text(_REPRODUCE_JUST)


def _cmd_reproduce(args: argparse.Namespace) -> int:
    runner.reproduce(args.dest)
    print(f"OK: reproduced {args.dest} faithfully at its recorded commit.")
    return 0


def _cmd_trust(args: argparse.Namespace) -> int:
    if args.trust_cmd == "add":
        added = trust.add_trust(args.prefix)
        print(f"{'added' if added else 'already trusted'}: {args.prefix}")
        return 0
    if args.trust_cmd == "list":
        entries = trust.list_trust()
        if entries:
            print("\n".join(entries))
        else:
            print("(no trusted sources)")
        return 0
    return 2


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="clerk", description="An agentic conductor for copier.")
    parser.add_argument("-V", "--version", action="version", version=f"clerk {__version__}")
    sub = parser.add_subparsers(dest="command")

    p_discover = sub.add_parser("discover", help="Inspect one template (static, JSON out).")
    p_discover.add_argument(
        "source", help="Fetchable template source (expanded https URL or path)."
    )
    p_discover.add_argument("--ref", default=None, help="Pin to a specific version/ref.")
    p_discover.set_defaults(func=_cmd_discover)

    p_init = sub.add_parser("init", help="Generate a project from a frozen run-spec.")
    p_init.add_argument(
        "--run-spec", required=True, help="Path to the inputs document (JSON/YAML)."
    )
    p_init.add_argument("--check", action="store_true", help="Dry-run validate; write nothing.")
    p_init.set_defaults(func=_cmd_init)

    p_repro = sub.add_parser("reproduce", help="Faithfully reproduce an existing project.")
    p_repro.add_argument("dest", nargs="?", default=".", help="Project directory (default: cwd).")
    p_repro.set_defaults(func=_cmd_reproduce)

    p_trust = sub.add_parser("trust", help="Manage trusted template sources.")
    trust_sub = p_trust.add_subparsers(dest="trust_cmd", required=True)
    p_trust_add = trust_sub.add_parser("add", help="Record a trusted source prefix (on consent).")
    p_trust_add.add_argument("prefix", help="Fully-expanded https prefix or exact URL to trust.")
    p_trust_add.set_defaults(func=_cmd_trust)
    p_trust_list = trust_sub.add_parser("list", help="List trusted sources.")
    p_trust_list.set_defaults(func=_cmd_trust)

    return parser


def main(argv: list[str] | None = None) -> int:
    """Entry point for the ``clerk`` console script."""
    args = argv if argv is not None else sys.argv[1:]
    parser = _build_parser()
    ns = parser.parse_args(args)
    if not getattr(ns, "command", None):
        parser.print_help()
        return 0
    try:
        return int(ns.func(ns))
    except UntrustedSourceError as exc:
        print(str(exc), file=sys.stderr)
        return 3
    except ClerkError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
