"""Combination stack: "Python service" — base + python + precommit + quality +
justfile + ci-github + dep-updates.

Verifies the frozen-union / single-writer contract (_cross-cutting §2/§4/§5/§6)
holds when the whole realistic stack composes:
- each module writes its own .mise/conf.d/<module>.toml fragment (no .mise.toml);
- precommit is the only writer of the hook config (contributed blocks present once);
- quality writes the quality-languages hook file;
- dep-updates defaults to renovate (R12: dep_update_tool no longer threaded from github_host).
"""

from __future__ import annotations

from pathlib import Path

import pytest
import yaml

from tests.integration.conftest import (
    RUFF_HOOK_BLOCK,
    init_stack,
)

_MISE_TOOLS = [{"python": "3.13"}, {"uv": "0.11.8"}]

_LAYERS = [
    (
        "bailiff-mod-base",
        {
            "project_name": "svc-demo",
            "org": "acme",
            "description": "A Python service",
            "license": "apache-2.0",
            "layout": "single",
            "github_host": True,
            "mise_tools": _MISE_TOOLS,
            "gitignore_stack": ["ghg:macOS", "Python"],
        },
    ),
    (
        "bailiff-mod-python",
        {
            "python_version": "3.13",
            "python_pkg_manager": "uv",
            "python_layout": "src",
            "ruff_line_length": "88",
            "hook_manager": "pre-commit",
        },
    ),
    (
        "bailiff-mod-precommit",
        {"hook_manager": "pre-commit", "hook_blocks": [RUFF_HOOK_BLOCK]},
    ),
    ("bailiff-mod-quality", {"quality_languages": ["python"]}),
    (
        "bailiff-mod-justfile",
        {"language": "python", "js_pkg_manager": "bun", "hook_manager": "pre-commit"},
    ),
    (
        "bailiff-mod-ci-github",
        {
            "ci_model": "standard",
            "ci_languages": ["python"],
            "ci_lang_facts": {
                "python": {"manager": "uv", "version": "3.13", "test_runner": "pytest", "image": ""}
            },
            "monorepo_tool": "none",
            "default_branch": "main",
        },
    ),
    # No dep_update_tool override — dep-updates defaults to renovate per R12.
    ("bailiff-mod-dep-updates", {"dep_ecosystems": ["uv", "github-actions"]}),
]


@pytest.fixture(scope="module")
def stack(tmp_path_factory: pytest.TempPathFactory) -> Path:
    root = tmp_path_factory.mktemp("stack_python_service")
    mp = pytest.MonkeyPatch()
    mp.setenv("COPIER_SETTINGS_PATH", str(root / "settings.yml"))
    try:
        yield init_stack(root, _LAYERS)
    finally:
        mp.undo()


def test_all_layers_rendered(stack: Path) -> None:
    """Every module's principal output landed; one answers file per layer."""
    for rel in (
        "AGENTS.md",  # base
        ".mise/conf.d/bailiff-mod-base.toml",  # base (014: per-module conf.d fragment)
        ".mise/conf.d/bailiff-mod-python.toml",  # python
        "ruff.toml",  # python
        "pyproject.toml",  # python (stubbed native init)
        ".pre-commit-config.yaml",  # precommit (single writer)
        ".agents/hooks/quality-languages",  # quality
        "justfile",  # justfile
        ".github/workflows/ci.yml",  # ci-github
    ):
        assert (stack / rel).is_file(), f"missing output: {rel}"
    assert not (stack / ".mise.toml").exists(), ".mise.toml must not exist in 014 model"
    answers = sorted(p.name for p in stack.glob(".copier-answers.*.yml"))
    assert len(answers) == len(_LAYERS), f"one answers file per layer, got {answers}"


def test_mise_conf_d_fragments(stack: Path) -> None:
    """014 model: each module writes its own .mise/conf.d/<module>.toml fragment."""
    # At least one conf.d fragment must exist.
    frags = list(stack.rglob(".mise/conf.d/*.toml"))
    assert len(frags) >= 1, "no .mise/conf.d/*.toml fragments found"
    python_frag = (stack / ".mise/conf.d/bailiff-mod-python.toml").read_text()
    assert 'python = "3.13"' in python_frag
    # No single .mise.toml exists in the 014 model.
    assert not (stack / ".mise.toml").exists(), ".mise.toml must not exist in 014 model"


def test_hook_file_single_writer_with_blocks(stack: Path) -> None:
    """precommit writes the hook file once; the frozen ruff block appears exactly once."""
    cfg = stack / ".pre-commit-config.yaml"
    text = cfg.read_text()
    assert "generated by _merge_precommit.py" in text
    assert text.count("ruff-pre-commit") == 1, "contributed block must appear exactly once"
    parsed = yaml.safe_load(text)
    repo_urls = [r.get("repo", "") for r in parsed["repos"]]
    assert any("ruff-pre-commit" in u for u in repo_urls), "block must parse into repos"
    # No second hook-manager file.
    assert not (stack / "lefthook.yml").exists()


def test_quality_languages_file(stack: Path) -> None:
    assert (stack / ".agents/hooks/quality-languages").read_text().split() == ["python"]


def test_justfile_python_recipes(stack: Path) -> None:
    justfile = (stack / "justfile").read_text()
    assert "uv run pytest" in justfile
    assert "pre-commit run --all-files" in justfile


def test_ci_workflow_python_jobs(stack: Path) -> None:
    ci = (stack / ".github/workflows/ci.yml").read_text()
    assert "# Model: standard" in ci
    assert "python-ci:" in ci
    assert "gate:" in ci


def test_dep_updates_defaults_to_renovate(stack: Path) -> None:
    """R12: github_host deleted from base; dep_update_tool defaults to renovate."""
    assert (stack / "renovate.json").exists(), "renovate.json must exist (default tool)"
    assert not (stack / ".github/dependabot.yml").exists(), "dependabot.yml must not exist"


# (reproduce byte-identity test removed — invariant is now config-consistency, spec 014)
